version: '3.8'

services:
  user-microservice:
    image: direstbounty/capstone2:user-microservice
    ports:
      - "8070:8070"
    networks:
      - aline-network
    environment:
      DB_USERNAME: root
      DB_PASSWORD: 12345678
      DB_HOST: host.docker.internal  # Use host.docker.internal for local db access
      DB_PORT: 3306
      DB_NAME: aline
      ENCRYPT_SECRET_KEY: your_encrypt_secret_key
      JWT_SECRET_KEY: 8RbnJKvEnaBqUtKP/oBZfSkxMni7O/R65EhPJCGDEVI=
      APP_PORT: 8070


  underwriter-microservice:
    image: direstbounty/capstone2:underwriter-microservice
    ports:
      - "8071:8071"
    networks:
      - aline-network  
    environment:
      DB_USERNAME: root
      DB_PASSWORD: 12345678
      DB_HOST: host.docker.internal  # Use host.docker.internal for local db access
      DB_PORT: 3306
      DB_NAME: aline
      ENCRYPT_SECRET_KEY: your_encrypt_secret_key
      JWT_SECRET_KEY: 8RbnJKvEnaBqUtKP/oBZfSkxMni7O/R65EhPJCGDEVI=
      APP_PORT: 8071
      

  account-microservice:
    image: direstbounty/capstone2:account-microservice
    ports:
      - "8072:8072"
    networks:
      - aline-network
    environment:
      DB_USERNAME: root
      DB_PASSWORD: 12345678
      DB_HOST: host.docker.internal  # Use host.docker.internal for local db access
      DB_PORT: 3306
      DB_NAME: aline
      ENCRYPT_SECRET_KEY: your_encrypt_secret_key
      JWT_SECRET_KEY: 8RbnJKvEnaBqUtKP/oBZfSkxMni7O/R65EhPJCGDEVI=
      APP_PORT: 8072
  transaction-microservice:
    image: direstbounty/capstone2:transaction-microservice
    ports:
      - "8073:8073"
    networks:
      - aline-network
    environment:
      DB_USERNAME: root
      DB_PASSWORD: 12345678
      DB_HOST: host.docker.internal  # Use host.docker.internal for local db access
      DB_PORT: 3306
      DB_NAME: aline
      ENCRYPT_SECRET_KEY: your_encrypt_secret_key
      JWT_SECRET_KEY: 8RbnJKvEnaBqUtKP/oBZfSkxMni7O/R65EhPJCGDEVI=
      APP_PORT: 8073

  bank-microservice:
    image: direstbounty/capstone2:bank-microservice
    ports:
      - "8083:8083"
    networks:
      - aline-network
    environment:
      DB_USERNAME: root
      DB_PASSWORD: 12345678
      DB_HOST: host.docker.internal  # Use host.docker.internal for local db access
      DB_PORT: 3306
      DB_NAME: aline
      ENCRYPT_SECRET_KEY: your_encrypt_secret_key
      JWT_SECRET_KEY: 8RbnJKvEnaBqUtKP/oBZfSkxMni7O/R65EhPJCGDEVI=
      APP_PORT: 8083

  aline-gateway:
    image: aline-gateway
    container_name: aline-gateway
    ports:
      - "8080:8080"
    networks:
      - aline-network
    environment:
      DB_USERNAME: root
      DB_PASSWORD: 12345678
      DB_HOST: host.docker.internal  
      DB_PORT: 3306
      DB_NAME: aline
      ENCRYPT_SECRET_KEY: your_encrypt_secret_key
      JWT_SECRET_KEY: 8RbnJKvEnaBqUtKP/oBZfSkxMni7O/R65EhPJCGDEVI=
      APP_PORT: 8080
    #add ip here  host: ""

  admin-portal:
    image: admin-portal  # Replace with your actual image
    ports:
      - "3000:3000"  # Adjust if your admin portal runs on a different port
    networks:
      - aline-network
    environment:
      API_URL: http://localhost:8080  # Adjust based on the actual API URL
      REACT_APP_API_BASEURL: http://localhost:8080/
      REACT_APP_TOKEN_NAME: aline_admin_token
      REACT_APP_BROKER_URL: ws://localhost:3000

  landing-page:
    image: direstbounty/capstone2:landing-page  # Replace with your actual image
    ports:
      - "3007:3000"  # Adjust if your landing page runs on a different port
    networks:
      - aline-network
    environment:
      API_URL: http://aline-gateway:8080  # Adjust based on the actual API URL

  member-dashboard:
    image: member-dashboard  # Replace with your actual image
    ports:
      - "4200:4200"  # Adjust if your dashboard runs on a different port
    networks:
      - aline-network
    environment:
      API_URL: http://aline-gateway:8080
      HOST: 0.0.0.0
    command: npm start --host=0.0.0.0 --port=4200   
networks:
  aline-network: